
# ---------------- Data ----------------
sensor_msgs/PointCloud2 input_cloud
sensor_msgs/Image image_front
sensor_msgs/Image image_rear

# ---------------- Camera Lens Properties ----------------
# NOTE - most image properties (height/width/frame/etc) given in image message 
# Specify projection type of lens 
#   1 -> EQUATORIAL STEROGRAPHIC 		 (Equidistant / Equal-angle / Stereographic Projection)
#   2 -> POLE-TANGENT STEREOGRAPHIC 	 (Equidistant / Equal-angle / Stereographic Projection)
#   3 -> LAMBERT ZENITHAL EQUAL AREA   	 (Equisolid   / Equal-area  / Lambert Azimuthal / Lambert Zenithal)
int32 projection
# Maximum FOV angle used by lens (degrees):
float32 max_angle

# ---------------- Compression ----------------
# ------ Raster-space Compression (simple) ------
bool compress_image
int32 image_compression_ratio
# ------ Pointcloud-space Voxelization ------
bool voxelize_rgb_images
float32 flat_voxel_size
float32 spherical_voxel_size
bool voxelize_depth_cloud
float32 depth_voxel_size

# ---------------- Processing ----------------
int32 neighbor_search_count
string camera_frame_front
string camera_frame_rear
string target_frame


---

sensor_msgs/PointCloud2 output_cloud